import {site} from './config.mjs';
import {services} from './services.mjs';

export const esc = (s='') => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arrow = '<span aria-hidden="true">↗</span>';
const icons = {
  energy: '<path d="M14 2 5 14h6l-1 8 9-12h-6l1-8Z"/>',
  electrical: '<path d="M8 3v5m8-5v5M6 8h12v3a6 6 0 0 1-6 6v5m-6-11a6 6 0 0 0 6 6"/>',
  gas: '<path d="M13 2c1 6-5 6-4 11 2-1 3-3 3-3 1 3 5 3 5 7a5 5 0 0 1-10 0C2 12 7 7 13 2Z"/>',
  shield: '<path d="M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6l-9-4Z"/><path d="m8 12 3 3 5-6"/>',
  document: '<path d="M5 2h9l5 5v15H5V2Z"/><path d="M14 2v6h5M8 12h8m-8 4h8"/>',
  phone: '<path d="M6 3h4l1 5-3 2a12 12 0 0 0 6 6l2-3 5 1v4c0 2-2 3-4 2C9 18 5 14 3 7 2 5 4 3 6 3Z"/>',
  chat: '<path d="M21 11a9 9 0 0 1-9 9H4l-2 2V11a9 9 0 0 1 19 0Z"/><path d="M7 10h10M7 14h6"/>',
};
export const icon = name => `<svg class="icon" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.35" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.document}</svg>`;
export const btn = (text, href='/contact/', secondary=false) => `<a class="button${secondary?' button-outline':''}" href="${esc(href)}">${text}${arrow}</a>`;
const textLink = (text, href) => `<a class="text-link" href="${esc(href)}">${text}${arrow}</a>`;
const email = `mailto:${site.email}`;
const wa = `https://wa.me/${site.whatsapp}`;
export const serviceLink = s => `/services/${s.slug}/`;
const eyebrow = text => `<p class="eyebrow">${text}</p>`;
const nav = [['Services','/services/'],['Landlord packages','/landlord-packages/'],['About us','/about/'],['Contact','/contact/']];

function header(path) {
  return `<a class="skip" href="#main">Skip to content</a>
  <div class="utility"><div class="container"><span>Homes. Investments. Peace of mind.</span><a href="tel:${site.phoneLink}">${icon('phone')} ${site.phone}</a></div></div>
  <header class="site-header"><div class="container nav-wrap">
  <a class="brand" href="/" aria-label="Property Fast home"><img src="/assets/logo.webp" alt="Property Fast — property compliance" width="280" height="94"></a>
  <button class="menu-toggle" aria-expanded="false" aria-controls="main-nav"><span>Menu</span><span class="menu-lines" aria-hidden="true"></span></button>
  <nav id="main-nav" aria-label="Main navigation">${nav.map(([t,u])=>`<a href="${u}"${path===u||(u==='/services/'&&path.startsWith(u))?' aria-current="page"':''}>${t}</a>`).join('')}${btn('Request a quote','/contact/')}</nav>
  </div></header>`;
}
function footer() {
  return `<footer class="footer"><div class="container footer-grid"><div class="footer-brand"><a href="/" aria-label="Property Fast home"><img src="/assets/logo.webp" alt="Property Fast" width="250" height="84"></a><p>Property compliance,<br>made straightforward.</p><a class="footer-call" href="tel:${site.phoneLink}">${site.phone}</a><a href="${email}">${site.email}</a></div>
  <div><p class="footer-heading">Explore</p><a href="/services/">Our services</a><a href="/landlord-packages/">Landlord packages</a><a href="/about/">About Property Fast</a><a href="/work-with-us/">Work with us</a><a href="/contact/">Request a quote</a></div>
  <div><p class="footer-heading">Popular services</p>${services.slice(0,5).map(s=>`<a href="${serviceLink(s)}">${s.short}</a>`).join('')}</div>
  <div class="footer-note"><p class="footer-heading">Let’s talk property.</p><p>Have a certificate to arrange or a question about your property? Start a conversation.</p>${textLink('Message on WhatsApp',wa)}<p class="small">Service coverage and appointment availability are confirmed when you enquire.</p></div>
  </div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} Property Fast</span><a href="/privacy/">Privacy &amp; website information</a></div></footer>
  <a href="${wa}" class="whatsapp" aria-label="Chat with Property Fast on WhatsApp" target="_blank" rel="noopener noreferrer">${icon('chat')}<span>Let’s talk</span></a>`;
}
export function layout(title, description, path, body) {
  return `<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><title>${esc(title)} | Property Fast</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${site.indexable?'index,follow':'noindex,nofollow'}"><meta name="theme-color" content="#6b2737"><meta property="og:title" content="${esc(title)} | Property Fast"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website">${site.url?`<link rel="canonical" href="${esc(site.url+path)}">`:''}<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/style.css"><script src="/assets/app.js" defer></script></head><body>${header(path)}<main id="main">${body}</main>${footer()}</body></html>`;
}
export function cta() {
  return `<section class="cta"><div class="container cta-inner"><div>${eyebrow('Your property. Our next conversation.')}<h2>Let’s get it<br><em>taken care of.</em></h2></div><div><p>Tell us what your property needs.<br>We’ll help you plan the next step.</p>${btn('Request a quote','/contact/')}<a class="cta-phone" href="tel:${site.phoneLink}">Prefer to call? ${site.phone}</a></div></div></section>`;
}
export function faq(items, title='A little clarity goes a long way.') {
  return `<section class="section faq-section"><div class="container two-column"><div>${eyebrow('Good to know')}<h2>${title}</h2><p>Can’t find the answer you need?<br><a class="underlined" href="/contact/">Ask us directly.</a></p></div><div class="faqs">${items.map(([q,a])=>`<details><summary>${esc(q)}<span aria-hidden="true">+</span></summary><p>${esc(a)}</p></details>`).join('')}</div></div></section>`;
}
const homeFaqs = [
  ['Which service does my property need?', 'That depends on the property, how it is used and what you are planning. Tell us whether you are selling, letting, managing or improving it, and we can discuss the relevant services.'],
  ['Can I arrange more than one service?', 'Yes. You can enquire about a combination of certificates, inspections and maintenance. We will confirm the scope and appointments before you commit.'],
  ['How much will it cost?', 'The service, property size and work required affect the price. Request a tailored quotation; no payment is taken through this website.'],
  ['Do you cover my postcode?', 'Share your postcode when you enquire. We will confirm service coverage and availability before any appointment is arranged.'],
];
export function home() {
  return `<section class="hero container"><div class="hero-copy">${eyebrow('Property compliance. Properly considered.')}<h1>Good homes.<br>Sound decisions.<br><em>Less to worry about.</em></h1><p class="hero-description">Certificates, inspections and essential property services. A straightforward way to look after the places that matter to you.</p><div class="hero-actions">${btn('Explore our services','/services/')}${textLink('Let’s talk','/contact/')}</div><div class="hero-footnote"><span class="line-mark"></span><p>For homeowners, landlords<br>and property professionals.</p></div></div><div class="hero-visual"><img src="/assets/architecture.webp" alt="Sunlit British townhouses with traditional entrance steps and a burgundy front door" width="1122" height="1402" fetchpriority="high"><div class="image-label"><span>THE PROPERTY FAST APPROACH</span><strong>Your property.<br>Our attention to detail.</strong><a href="/about/" aria-label="Discover the Property Fast approach">${arrow}</a></div><div class="image-caption">A clearer way to care for property.</div></div></section>
  <div class="service-ribbon"><div class="container"><span>One point of contact</span><span>EPC &amp; energy</span><span>Electrical safety</span><span>Gas &amp; heating</span><span>Property surveys</span></div></div>
  <section class="section container"><div class="section-heading"><div>${eyebrow('01 / Our services')}<h2>The right service.<br><em>For your property.</em></h2></div><p>From a single certificate to a more involved project, start with the service you need. We’ll help with the details.</p></div><div class="featured-services">${services.slice(0,3).map((s,i)=>`<a class="service-feature" href="${serviceLink(s)}"><div class="service-feature-top">${icon(s.icon)}<span>0${i+1}</span></div><h3>${s.short==='EPC'?'Energy performance':s.short==='EICR'?'Electrical safety':'Gas safety'}</h3><p>${esc(s.description)}</p><div class="service-feature-bottom"><span>${i===0?'EPC certificates':i===1?'EICR reports':'Gas safety records'}</span>${arrow}</div></a>`).join('')}</div><div class="services-after"><p>Also here for PAT testing, fire risk assessments, inventories and more.</p>${textLink('View all services','/services/')}</div></section>
  <section class="landlord-section"><div class="container landlord-grid"><div class="landlord-title">${eyebrow('02 / For landlords & managing agents')}<h2>More properties.<br><em>Fewer loose ends.</em></h2><p>One property or a growing portfolio. Bring your inspection and certificate enquiries together, with a package shaped around what you actually need.</p>${btn('Discover landlord packages','/landlord-packages/',true)}</div><div class="package-preview"><div class="package-top"><span>THE LANDLORD ESSENTIALS</span>${icon('document')}</div><h3>A considered<br>combination.</h3><ul><li><span>01</span>Energy Performance Certificate</li><li><span>02</span>Electrical Condition Report</li><li><span>03</span>Gas Safety Check</li></ul><p>Scope and pricing tailored to your property.</p>${textLink('Build your package','/contact/?service=Landlord%20essentials')}</div></div></section>
  <section class="section container process"><div class="section-heading"><div>${eyebrow('03 / How it works')}<h2>From first enquiry<br><em>to the final detail.</em></h2></div><p>Clear expectations at every step. No complicated sign-ups, no guessing what comes next.</p></div><div class="steps">${[['Tell us what you need','Share your service, postcode and property details. Not sure where to start? Just ask.'],['Agree the details','We’ll confirm the scope, quotation and appointment arrangements with you.'],['Keep things moving','Arrange access for the visit, then receive the relevant report and understand your next steps.']].map(([t,d],i)=>`<article><span class="step-number">0${i+1}</span><h3>${t}</h3><p>${d}</p></article>`).join('')}</div></section>
  <section class="approach-strip"><div class="container"><p>“Property care should feel<br><em>clear, not complicated.</em>”</p><div>${eyebrow('The Property Fast approach')}<span>Useful advice. Clear scope.<br>A straightforward conversation.</span>${textLink('Get to know us','/about/')}</div></div></section>
  ${faq(homeFaqs)}${cta()}`;
}
export function intro(kicker,title,desc) {
  return `<section class="page-intro container"><a class="breadcrumb" href="/">Home <span>/</span></a>${eyebrow(kicker)}<h1>${title}</h1><p>${desc}</p></section>`;
}
export function servicesPage() {
  return `${intro('Services, with the details in mind.','A little care.<br><em>A lot of reassurance.</em>','Explore certificates, inspections and essential maintenance for your property. Every enquiry starts with understanding what you need.')}<section class="container section service-directory"><div class="filter-bar" role="group" aria-label="Filter services">${['All services','Certificates & surveys','Electrical','Gas & plumbing'].map((g,i)=>`<button type="button" data-filter="${esc(g)}" aria-pressed="${i===0}">${esc(g)}</button>`).join('')}</div><p id="filter-count" class="small" aria-live="polite">${services.length} services</p><div class="directory-grid">${services.map(s=>`<article class="directory-item" data-group="${esc(s.group)}"><div>${icon(s.icon)}<span class="small">${esc(s.group)}</span></div><h2><a href="${serviceLink(s)}">${esc(s.title)}</a></h2><p>${esc(s.description)}</p>${textLink('Explore service',serviceLink(s))}</article>`).join('')}</div><noscript><p>All services are shown. You can open each service directly.</p></noscript></section>${cta()}`;
}
export function detailPage(s) {
  return `<section class="service-hero"><div class="container"><a class="breadcrumb" href="/services/">Services <span>/ ${esc(s.short)}</span></a><div class="service-hero-grid"><div>${eyebrow(s.group)}<h1>${esc(s.title)}</h1><p class="service-tagline">${esc(s.intro)}</p><p>${esc(s.description)}</p>${btn('Request a quote',`/contact/?service=${encodeURIComponent(s.title)}`)}</div><div class="service-symbol">${icon(s.icon)}<span>${esc(s.short)}</span></div></div></div></section>
  <section class="section container detail-grid"><div class="service-body">${eyebrow('The overview')}<h2>Know what<br><em>you’re arranging.</em></h2><p>${esc(s.body)}</p><p>${esc(s.detail)}</p><h3>What the service can include</h3><ul class="check-list">${s.includes.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div><aside class="service-aside"><span class="eyebrow">At a glance</span><dl><dt>Suitable for</dt><dd>${esc(s.audience)}</dd><dt>Price</dt><dd>Tailored quotation</dd><dt>Availability</dt><dd>Confirmed for your postcode</dd></dl><h3>Before the visit</h3><ol>${s.prepare.map(t=>`<li>${esc(t)}</li>`).join('')}</ol>${textLink('Ask a question','/contact/')}</aside></section>
  ${faq(s.faqs,'Your questions,<br><em>answered.</em>')}<section class="section container related"><div class="section-heading"><div>${eyebrow('You may also need')}<h2>Look at the<br><em>bigger picture.</em></h2></div>${textLink('All services','/services/')}</div><div class="related-links">${services.filter(x=>x.slug!==s.slug).slice(0,3).map(x=>`<a href="${serviceLink(x)}">${icon(x.icon)}<span>${esc(x.title)}</span>${arrow}</a>`).join('')}</div></section>${cta()}`;
}
export function packagesPage() {
  const packs=[['01','Landlord essentials','Bring your key certificate enquiries together.',['EPC assessment','EICR inspection','Gas safety check'],'For an individual rental property'],['02','Tenancy ready','Prepare the paperwork around a property handover.',['EPC, EICR & gas enquiries','Inventory or condition report','PAT testing if required'],'For a new tenancy or changeover'],['03','Portfolio care','A coordinated conversation for multiple properties.',['Property-by-property scope','Combined service enquiries','Phased appointment planning'],'For agents and portfolio landlords']];
  return `${intro('Landlord packages','One conversation.<br><em>More things taken care of.</em>','Combine the services that make sense for your property. We’ll confirm what is included, what can be coordinated and the price before anything is booked.')}<section class="container packages-grid">${packs.map(([n,t,d,l,f],i)=>`<article class="package-full ${i===0?'package-primary':''}"><span class="eyebrow">PACKAGE / ${n}</span><h2>${t}</h2><p>${d}</p><span class="package-price">Quoted for your property</span><ul class="check-list">${l.map(x=>`<li>${x}</li>`).join('')}</ul><p class="small">${f}</p>${btn('Discuss this package',`/contact/?service=${encodeURIComponent(t)}`,i!==0)}</article>`).join('')}</section><section class="section container two-column"><div>${eyebrow('Built around the property')}<h2>Not everything needs<br><em>the same checklist.</em></h2></div><div><p>A flat, a family home and a commercial premises have different needs. Existing certificates, appliance counts and your plans for the property all matter.</p><p>Packages are starting points for a quotation, not a promise that every service applies to every property. Visits may involve different specialists and appointment times.</p>${textLink('Tell us about your property','/contact/')}</div></section>${faq(homeFaqs.slice(1,4))}${cta()}`;
}
export function aboutPage() {
  return `${intro('About Property Fast','Property matters.<br><em>So do the details.</em>','A straightforward point of contact for property certificates, inspections and essential services.')}<section class="container about-grid"><img src="/assets/architecture.webp" alt="Traditional townhouse entrance and carefully maintained architectural details" width="1122" height="1402" loading="lazy"><div>${eyebrow('Our approach')}<h2>Less uncertainty.<br><em>More understanding.</em></h2><p>Property ownership comes with plenty to organise. Knowing which inspection to arrange, what a report covers or how to plan the next piece of work should not add another layer of confusion.</p><p>Property Fast brings those conversations together. We start with the property and your plans for it, then help clarify the service, scope and next step.</p><p>From homeowners and individual landlords to letting agents and property managers, our focus is the same: useful information and a well-considered service.</p>${textLink('Talk to Property Fast','/contact/')}</div></section><section class="section container"><div class="section-heading"><div>${eyebrow('What matters to us')}<h2>A better way<br><em>to get things organised.</em></h2></div></div><div class="steps">${[['Clarity first','Understand the proposed service and quotation before making a decision.'],['The right scope','Discuss the property, the circumstances and the information needed for the job.'],['Attention to detail','Keep access arrangements, documentation and next steps part of the conversation.']].map(([t,d],i)=>`<article><span class="step-number">0${i+1}</span><h3>${t}</h3><p>${d}</p></article>`).join('')}</div></section>${cta()}`;
}
function enquiryForm(work=false) {
  return `<form class="enquiry-form" data-enquiry data-email="${site.email}" data-whatsapp="${site.whatsapp}" action="/api/contact" method="post"><input type="hidden" name="type" value="${work?'contractor':'quote'}"><div class="hp" aria-hidden="true"><label>Leave blank<input name="website" type="text" tabindex="-1" autocomplete="off"></label></div><div class="form-row"><label>Your name <span>*</span><input name="name" autocomplete="name" required maxlength="100" placeholder="Full name"></label><label>Email address <span>*</span><input name="email" type="email" autocomplete="email" required maxlength="180" placeholder="you@example.com"></label></div><div class="form-row"><label>Phone number<input name="phone" type="tel" autocomplete="tel" maxlength="30" placeholder="Your contact number"></label><label>${work?'Operating postcode':'Property postcode'} <span>*</span><input name="postcode" autocomplete="postal-code" required maxlength="12" placeholder="e.g. SW1A 1AA"></label></div><label>${work?'Your trade or service':'What can we help with?'} <span>*</span><select name="service" required><option value="">Please select</option>${services.map(s=>`<option value="${esc(s.title)}">${esc(s.title)}</option>`).join('')}<option>Landlord essentials</option><option>Tenancy ready</option><option>Portfolio care</option><option>Something else / not sure</option></select></label><label>${work?'Tell us about your work':'A little about your property'} <span>*</span><textarea name="message" rows="5" required minlength="10" maxlength="3000" placeholder="${work?'Your experience, accreditations, services and coverage areas. Please do not include identity or banking documents.':'Property type, services needed, preferred timing and anything else that would help.'}"></textarea></label><label class="consent"><input type="checkbox" name="consent" required><span>I agree to Property Fast using these details to respond to my enquiry. <a href="/privacy/">Privacy information</a>.</span></label><button class="button form-submit" type="submit">${work?'Send your introduction':'Request a quote'}${arrow}</button><p class="form-status" role="status" aria-live="polite"></p><div class="form-alternatives" hidden><p>Your message has <strong>not</strong> been sent. Choose an alternative to review and send it:</p><a class="button button-outline" data-email-fallback href="${email}">Open email app ${arrow}</a><a class="text-link" data-wa-fallback href="${wa}" target="_blank" rel="noopener noreferrer">Continue on WhatsApp ${arrow}</a></div><p class="small">${work?'An enquiry does not create an account or confirm a partnership.':'An enquiry is not a confirmed booking. No payment is taken here.'}</p><noscript><p>To enquire without JavaScript, email <a href="${email}">${site.email}</a> or call <a href="tel:${site.phoneLink}">${site.phone}</a>.</p></noscript></form>`;
}
export function contactPage(work=false) {
  return `${intro(work?'Work with Property Fast':'Start a conversation',work?'Good people.<br><em>Well-considered work.</em>':'Your property.<br><em>Let’s talk about it.</em>',work?'An assessor, engineer or property specialist? Tell us about your work and where you operate.':'Tell us what you need, or ask us where to start. We’ll discuss the service, location and next steps with you.')}<section class="container contact-grid"><aside class="contact-aside">${eyebrow(work?'Introduce yourself':'A direct line')}<h2>${work?'Build a working<br>relationship.':'People first.<br>Property second.'}</h2><p>${work?'Share your trade, relevant qualifications and coverage. Any partnership is subject to verification and agreement.':'A single certificate or several services. One home or a portfolio. We’re here to discuss it.'}</p><div class="contact-method"><span>Call us</span><a href="tel:${site.phoneLink}">${site.phone}</a></div><div class="contact-method"><span>Email us</span><a href="${email}">${site.email}</a></div><div class="contact-method"><span>Message us</span><a href="${wa}" target="_blank" rel="noopener noreferrer">WhatsApp ${arrow}</a></div><p class="small">Share your postcode to confirm coverage and appointment availability.</p></aside><div class="form-panel"><h2>${work?'Tell us about yourself.':'How can we help?'}</h2><p>Fields marked * are required.</p>${enquiryForm(work)}</div></section>`;
}
export function privacyPage() {
  return `${intro('Privacy & website information','Your information.<br><em>Handled with care.</em>','How this website handles enquiries and the details you choose to share.')}<section class="container prose section"><h2>Contacting Property Fast</h2><p>When you send an enquiry, the details you provide are used to discuss your request, prepare a response and, where appropriate, arrange services. You can contact Property Fast at <a href="${email}">${site.email}</a> about the information you have supplied.</p><h2>Information you choose to provide</h2><p>The enquiry forms ask for your name, email, optional phone number, postcode, service and message. Please do not include payment details, passwords, identity documents or other sensitive information.</p><h2>Sending an enquiry</h2><p>When the website’s email service is available, the form sends your enquiry to Property Fast. If it is unavailable, the website will say that your message has not been sent and offer an email-app or WhatsApp alternative. Those alternatives open another service for you to review and send the message yourself.</p><h2>Website operation</h2><p>This version of the website does not use advertising trackers or marketing cookies. The hosting service may process technical request information needed to serve and protect the website. Enquiry delivery uses the configured email provider when enabled. Messages sent through WhatsApp or your email application are also handled by those services.</p><h2>Your choices</h2><p>You may ask Property Fast about the information held in connection with your enquiry, or request a correction or deletion. Contact the email address above with enough detail to identify the correspondence. Do not send identification documents unless they are specifically required and a suitable transfer method has been agreed.</p><h2>Service information</h2><p>Website content is general information, not property-specific legal or technical advice. Service scope, availability, pricing and any applicable contractual terms are confirmed directly before a booking. Illustrative architectural imagery is not evidence of completed work. No third-party accreditation or customer-review claims are made.</p><p class="small">Website information updated 21 September 2026.</p></section>`;
}
